### ISSUE TITLE
pint-deploy tool to deploy contracts

### ISSUE THREAD

**Issue by supiket** [essential-contributions/essential-integration#123]
Tool that:

- Takes in a builder address, an optional path to a Pint manifest file and an optional path to a folder that contains contract artifacts.
- If none of the optionals are provided, searches for a Pint manifest and builds the Pint project. 
- If Pint manifest file is provided, builds Pint project.
- If path to artifacts are provided, skips building step.
- Submits solutions to the contract registry contract using EssentialBuilderClient. 
- Prints out information about deployed contracts in success scenario.

**Comment by mitchmindtree** [comment]
Also related: [this comment](https://github.com/essential-contributions/essential-integration/pull/121#discussion_r1844904067).

**Comment by mitchmindtree** [comment]
Going to take over on this after #121 lands and address the above comment
