### ISSUE TITLE
Add a Nix flake example in the Getting Started Guide

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/essential-integration#52]
In docs/getting-started/src/getting-started/counter/app/index.md

I took that stuff out for now until we actually add the example.

**Comment by freesig** [comment]
What does this issue mean? There is a nix example on that page

**Comment by mohammadfawaz** [comment]
I'm referring to this change that I made last week:
<img width="1696" alt="image" src="https://github.com/user-attachments/assets/b01cc6d1-9972-4577-9c43-d568b2199799">
I removed the TODO so that it's not visible when we open sourced, but I thought I'd open this issue so that we don't forget about it.

**Comment by freesig** [comment]
Ah yeh nice spot
